### DISCUSSION TITLE
Add a setting to control a site's default theme selection (light/dark/auto)

### DISCUSSION THREAD

**Discussion by ghost** [thegeeklab/hugo-geekdoc#120] [Ideas]
It would be neat if it was possible to control the default theme selection with a setting in your `config.toml` file, e.g. like this:

```toml
[params]
  # (Optional, default auto) Specify the default theme selection for your site.
  # The available options are `light`, `dark` and `auto`
  geekdocDefaultThemeSelection = "auto"
```
