### DISCUSSION TITLE
Rendering logo from URL

### DISCUSSION THREAD

**Discussion by jamesbraza** [thegeeklab/hugo-geekdoc#635] [Q&A] [answered]
Is it possible for `geekdocLogo` to be rendered from a URL (as opposed to local file in `static/`)?

**Comment by xoxys** [comment, marked as answer]
It's using an `<img src=...>` which also allows full URLs. So yes, external URLs should work.

**Reply by jamesbraza** [reply]
Thank you!  Yes this is working in my `hugo.toml`:

```toml
[params]
  # (Optional, default static/brand.svg) Set the path to a logo for the Geekdoc
  # relative to your 'static/' folder.
  geekdocLogo = "https://upload.wikimedia.org/wikipedia/commons/0/0a/Python.svg"
```

@xoxys do you think this is worth updating the comment in the Configuration instructions?
