### DISCUSSION TITLE
Why does page-header.html partial use ` .File.Filename` instead of `.File.Path` ?

### DISCUSSION THREAD

**Discussion by p0lygun** [thegeeklab/hugo-geekdoc#709] [Q&A]
I know it might seem like a dumb question but in my project, I use `[[module.mounts]]` to mount dir into `content` dir,  

but as the theme uses `File.Filename` the resolved path is absolute and the `strings.TrimPrefix` does not actually remove the local dir.  

to give an example consider
```
docs/
└──portal_blocks\
    └──_index.html
 └── _index.html

hugo/
└──content/
 └── config.toml
```
in my `config.toml` I have

```toml
[[module.mounts]]
source = "../docs/"
target = "./content/"
excludeFiles = ["portal_blocks/**"]
```

upon rendering the path resolved becomes `/home/user/...../docs/_index.html` as `strings.TrimPrefix`  as  no overlap to trim, 
using `.File.Path` resolves it correctly
