### ISSUE TITLE
Allow alphabetical sorting in multilanguage bundle menu

### ISSUE THREAD

**Issue by d1nuc0m** [thegeeklab/hugo-geekdoc#388]
Hi, I ran in to a possible issue with bundle menu and multilanguage.
Suppose to have a menu like this:

```
main:
  - name:
      en: Lorem Ipsum
      it: Minim veniam
     ref: "myPage"
  - name:
      en: Ut enim
      it: Dolor sit
     ref: "myPage2"
```
 The English menu would be alphabetically ordered:

- Lorem Ipsum
- Ut enim

While the Italian one would not:
- Minim veniam
- Dolor sit

(Obiviously with only two entries is not a problem).

Maybe an option to alphabetically sort the pages that are at the same level/sublevel could be useful? Or is it a too-specific use case?
