### ISSUE TITLE
Markdown header link stripped from main menu ref

### ISSUE THREAD

**Issue by jcrd** [thegeeklab/hugo-geekdoc#467]
Using `v0.33.2`.

Given the following main menu item:
```yml
main:
  - name: Usage
    ref: "/usage.md"
    sub:
      - name: Starting the session
        ref: "/usage.md#starting-the-session"
```
The markdown header link (`#starting-the-session`) in the sub menu ref is stripped from the generated `href`:
```html
<span class="flex">     
    <a
        href="/usage/"
        class="gdoc-nav__entry"
    >
    Starting the session
    </a>
</span>
```

**Comment by xoxys** [comment]
Thanks for your report. Indeed, that's due to how the menu is build. We use Hugos [GetPage](https://gohugo.io/functions/getpage/) function to get a proper page object from the given `ref` attribute. As `GetPage` removes the anchor completely, it's not possible to use anchors in `ref` this way.

I have prepared a PR to add a new attribute `rawref` to the menu data file. This attribute can be set to `true` to use Hugos [relref](https://gohugo.io/functions/relref/) function (which supports anchors) instead of `GetPage`.

**Comment by xoxys** [comment]
I had to change the approach a bit to avoid issues on multilang sites. The PR adds a new option `anchor` that need to be used instead:

```YAML
main:
  - name: Link with Anchor
    ref: "/usage/getting-started"
    anchor: using-the-theme
```

```HTML
<a href="/usage/getting-started/#using-the-theme" class="gdoc-nav__entry is-active">
  Link with Anchor
</a>
```
