### ISSUE TITLE
img shortcode generates nothing

### ISSUE THREAD

**Issue by reid-spencer** [thegeeklab/hugo-geekdoc#498]
I've tried all manner of things but have not succeeded to make the `img` shortcode generate anything in 0.35.2 or 0.34.2

My resource is defined like this:

```yaml
resources:
  - name: entities
    src: "/images/entities.png"
    title: Entity Equivalence
    params:
      credits: "[Lightbend](https://lightbend.com/)"
```

My image file is in static/images/entities.png. You can view it here: http://riddl.tech/images/entities.png

My usage is like this, per the documentation here: https://geekdocs.de/shortcodes/images/#usage

```markdown
{{< img name="entities" size="origin" lazy="false" >}}
```

The source is located here:  https://github.com/reactific/riddl/edit/main/doc/src/hugo/content/concepts/entity.md

Any help would be greatly appreciated. Thanks!
