### ISSUE TITLE
Title of links aren't properly localized

### ISSUE THREAD

**Issue by KwadroNaut** [thegeeklab/hugo-geekdoc#683]
The title attribute at the bottom isn't translated. Screenshot: 

![image](https://github.com/thegeeklab/hugo-geekdoc/assets/99527/9727ab7c-b519-4633-a33d-f9fb91a80451)

**Comment by xoxys** [comment]
How does your `menu/main.yml` file look like?

**Comment by xoxys** [comment]
This should work already with the correct structure in `menu/main.yml`  according to https://github.com/thegeeklab/hugo-geekdoc/blob/main/exampleSite/data/menu/main.yaml

Closing due to missing feedback.

**Comment by KwadroNaut** [comment]
> How does your `menu/main.yml` file look like?

This is what it looks like:
```
---
main:
  - name:
      en: Welcome
      de: Grüße
      ru: привет
    ref: "/"
  - name:
      en: Overview
      de: Überblick
      ru: обзор
    ref: "/overview"
  - name:
      en: Circumvention
      de: Umgehung
      ru: Обход
    ref: "/circumvention/"
  - name:
      en: Tutorials
      de: Tutorials
      ru: учебники
    ref: "/tutorials"
```
