### ISSUE TITLE
Category needs to have a ref in bundle menu in order for it to be collapseable

### ISSUE THREAD

**Issue by Miepee** [thegeeklab/hugo-geekdoc#738]
Assuming I have something like this as my `main.yaml`:
```yaml
- name: root
  sub:
    - name: foo
      ref: "/root/foo"
    - name: bar
      ref: "/root/bar"
  ```
and the `_index.md` for root only consists of this:
```md
---
title: Root
geekdocCollapseSection: true
--- 
```
Then the `Root` category will not be collapseable.
