### ISSUE TITLE
Make UI for expandable shortcodes clearer

### ISSUE THREAD

**Issue by Miepee** [thegeeklab/hugo-geekdoc#828]
From just looking at this image, it's not immediately clear that this can be clicked to get expanded:
![grafik](https://github.com/thegeeklab/hugo-geekdoc/assets/38186597/01eaaba1-54e7-49fd-8232-2cb3e4231a2d)

It'd be nice if on the far left, there would be a `>`/`v` similar to GH's spoiler element:
<details> 
  <summary>Custom Label</summary>
  
   ### More markdown
  Dolor sit, sumo unique ...
  
</details>

**Comment by xoxys** [comment]
To be honest, personally, I like the way it is. As this can be easily customized by custom CSS I would like to close this one as "wont fix". Hope that makes sense for you.

Example:

```css
.gdoc-expand__head.flex {
  flex-direction: row-reverse;
  justify-content: flex-end;
  gap: 0.5em;
}
```

![image](https://github.com/thegeeklab/hugo-geekdoc/assets/3391958/f931e880-f03c-40ac-b0b7-6c4736811a77)
