### ISSUE TITLE
Feature request: Add rel property in menu bundles

### ISSUE THREAD

**Issue by MayeulC** [thegeeklab/hugo-geekdoc#878]
Rationale: Including a `rel="me"` property in a link is sometimes required for website verification, in [mastodon](https://joinmastodon.org/verification) and others.

References:
* https://microformats.org/wiki/rel-me
* https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/me

There are [other](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel) possible rel types, and they don't all make sense in this context, but I don't think allowing them is an issue.

Possible implementation (untested):
```diff
diff --git a/layouts/partials/menu-bundle.html b/layouts/partials/menu-bundle.html
index d9dcfbb..a158191 100644
--- a/layouts/partials/menu-bundle.html
+++ b/layouts/partials/menu-bundle.html
@@ -60,6 +60,9 @@
                   class="gdoc-nav__entry{{- if not .external }}
                     {{- if $isCurrent }}{{ printf " is-active" }}{{ end }}
                   {{- end }}"
+                 {{ if .rel - }}
+                   rel="{{ .rel }}"
+                 {{ - end }}
                 >
                   {{ $name }}
                 </a>
```

The idea is to add the ability to put links with the `rel="me"` property in the sidebar:

```yaml
# data/menu/more.yaml
more:
  - name: "My mastodon account"
    ref: "https://mastodon.example.com/my-account"
    external: true
    rel: me
```
